# Generated by Django 4.2.5 on 2023-09-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_news_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newssource',
            options={},
        ),
        migrations.RemoveField(
            model_name='newssource',
            name='id_name',
        ),
        migrations.AddField(
            model_name='newssource',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
